networks:
  myappnetwork:
    driver: bridge

volumes:
  volume_data_test:
    driver: local

services:
  mysql:
    container_name: mysql-container-doctor-appointment-api
    image: mysql:8.0
    volumes:
      - volume_data_test:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: doctor_appointment_api
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    networks:
      - myappnetwork
    restart: always

  service:
    container_name: service-container-doctor-appointment-api
    image: "oliver005/doctor_appointment_api:10.05.2025.22.12.48-test"
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
    networks:
      - myappnetwork

  client:
    container_name: client-container-doctor-appointment-api
    image: "oliver005/doctor-appointment-frontend-react:10.05.2025.23.00.30-prod"
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - service
    networks:
      - myappnetwork