spring:
  application:
    name: doctor-appointment-api

  datasource:
    url: jdbc:mysql://mysql:3306/doctor_appointment_api?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    hikari:
      maximum-pool-size: 15
      connection-timeout: 30000
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=300s

logging:
  level:
    root: INFO
    mycode.doctor_appointment_api: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
      
# Docker JWT settings
jwt:
  secret: ${JWT_SECRET:docker-secret-key}
  expiration: ${JWT_EXPIRATION:7200000} # 2 hours