name: CD - Deploy Doctor Appointment App

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build and push
        run: |
          chmod +x ci/build.sh
          ci/build.sh prod
  deploy-ec2:
    needs: deploy
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Update tag & restart client
        uses: appleboy/ssh-action@v0.1.10
        env:
          COMPOSE_PROJECT_NAME: doctorapp
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -euo pipefail
            
            ENV_FILE=/home/ubuntu/.env
            NEW_TAG="${{ needs.build-client.outputs.tag }}"
            
            echo "🔄  Set CLIENT_TAG=$NEW_TAG"
            if grep -q '^CLIENT_TAG=' "$ENV_FILE"; then
              sudo sed -i "s/^CLIENT_TAG=.*/CLIENT_TAG=$NEW_TAG/" "$ENV_FILE"
            else
              echo "CLIENT_TAG=$NEW_TAG" | sudo tee -a "$ENV_FILE"
            fi
            
            echo "🚢  Pull & restart client"
            # dacă fișierul tău se numește docker-compose.yml, schimbă extensia aici
            sudo docker compose -f /home/ubuntu/docker-compose.yaml pull client
            sudo docker compose -f /home/ubuntu/docker-compose.yaml up -d --no-deps client