name: CD - Deploy Doctor Appointment App

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build and push
        run: |
          chmod +x ci/build.sh prod
          USERNAME=oliver005 \
          REPO=doctor_appointment_api \
          TAG=${{ env.BUILD_NUMBER }} \
          ci/build.sh prod ./